### ISSUE TITLE
[Feature Request] Scenario cards

### ISSUE THREAD

**Issue by ediebold** [spirit-island-builder/spirit-island-builder#447]
Hi! I'd love for the ability to make my own scenario cards!

**Comment by resonant-gamedesign** [comment]
@ediebold https://dev.spirit-island-builder-2.pages.dev/
Up for testing

**Comment by ediebold** [comment]
@resonant-gamedesign Thanks! This is amazing. A few minor issues with spacing, and the Examples link still shows the examples for Adversaries, but this is basically perfect!
![Uploading Reach_of_The_Abyss_Scenario.png…]()

**Comment by ediebold** [comment]
![Reach_of_The_Abyss_Scenario](https://github.com/spirit-island-builder/spirit-island-builder/assets/3262375/61076f5b-8a35-4da1-b818-71125666b900)

**Comment by resonant-gamedesign** [comment]
Could you email your save file to resonant@spiritislandbuilder.com

**Comment by resonant-gamedesign** [comment]
I've fixed some of these issues on dev
https://dev.spirit-island-builder-2.pages.dev/

**Comment by ediebold** [comment]
Hi! Looks better now for sure.

I have used the built-in bullet lists, and I'm still not seeing the space after them.

[Reach_of_The_Abyss_Scenario.html.zip](https://github.com/spirit-island-builder/spirit-island-builder/files/15172970/Reach_of_The_Abyss_Scenario.html.zip)

**Comment by resonant-gamedesign** [comment]
Got it, yeah. I've got a fix in the pipeline
